version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    container_name: petstoredb
    volumes:
      - ./postgres:/var/lib/postgresql/data

      # to get postgresql up and running
      # docker-compose up -d
      # docker exec -it teslodb psql -U postgres
